import type { Metadata } from "next";
import { Sedgwick_Ave_Display, Fredoka } from "next/font/google";
import "./globals.css";

const sedgwick = Sedgwick_Ave_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sedgwick",
});

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-fredoka",
});



export const metadata: Metadata = {
  title: "SnapSpeaks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${sedgwick.variable} ${fredoka.variable} antialiased font-sans bg-background text-foreground`}
>
        {children}
       </body>
    </html>
  );
}
